name: 'checkout-helm-versions'
description: 'Action to do a sparse checkout of environments and versions directories from https://github.com/broadinstitute/terra-helmfile/'
author: 'ichengchang'
inputs:
  repository:
    description: 'terra-helmfile repo'
    required: true
    default: 'broadinstitute/terra-helmfile'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
    default: 'master'
  token:
    description: 'Access token used to fetch the repository'
    required: true
    default: ''
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the checkout directories'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Sparse checkout https://github.com/broadinstitute/terra-helmfile/
      id: sparse-checkout
      run: |
        mkdir -p ${{ inputs.path }}
        cd ${{ inputs.path }}
        git init
        git remote add origin https://${{ inputs.token }}@github.com/${{ inputs.repository }}
        git fetch --all --quiet
        git config core.sparseCheckout true
        if [ -f .git/info/sparse-checkout ]; then
          rm .git/info/sparse-checkout
        fi
        echo "environments/" >> .git/info/sparse-checkout
        echo "versions/" >> .git/info/sparse-checkout
        git checkout ${{ inputs.ref }}
      shell: bash
