version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 10
    groups:
      minor-patch-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "spotless-plugin-gradle" # likely to require reformatting of code
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "America/New_York"
    target-branch: "main"
    reviewers:
      - "@DataBiosphere/broad-core-services"
    labels:
      - "dependency"
      - "gradle"
    commit-message:
      prefix: "[CORE-69]"
    ignore:
      - dependency-name: "com.google.apis:google-api-services-iam"
      - dependency-name: "com.google.apis:google-api-services-notebooks"
      # From 20.0.0 onward, k8s client publishes versions with and without '-legacy' suffix.
      # We use the non-legacy client: the legacy client is not compatible with our code.
      # Dependabot doesn't have an option for ignoring versions conforming to a naming convention
      # (outside of semver major, minor, and patch designations) and will attempt to update
      # to the latest published version.
      - dependency-name: "io.kubernetes:client-java"
