CREATE DATABASE testdb;
CREATE ROLE dbuser WITH LOGIN ENCRYPTED PASSWORD 'dbpwd';
CREATE DATABASE stairwaylib;
CREATE ROLE stairwayuser WITH LOGIN ENCRYPTED PASSWORD 'stairwaypwd';
CREATE DATABASE wm;
CREATE ROLE wmuser WITH LOGIN ENCRYPTED PASSWORD 'wmpwd';
