spring:
  cloud.gcp.trace.project-id: broad-dsde-prod

workspace:
  datarepo.instances:
    terra: https://jade-terra.datarepo-prod.broadinstitute.org

  sam.base-path: https://sam.dsde-prod.broadinstitute.org/
