#This is a Skaffold configuration, which lets developers continuously push new images to their development namespaces.
apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
    - image: gcr.io/terra-kernel-k8s/jmeter-director
      context: jmeter-director
      docker: {}
    - image: gcr.io/terra-kernel-k8s/jmeter-worker
      context: jmeter-worker
      docker: {}
deploy:
  helm:
    releases:
      - name: jmeter-director-worker
        namespace: terra-jmeter
        chartPath: terra-helm/charts/jmeter-cluster
        skipBuildDependencies: true
        values:
          directorImage: gcr.io/terra-kernel-k8s/jmeter-director
          workerImage: gcr.io/terra-kernel-k8s/jmeter-worker
        valuesFiles:
          - terra-helmfile/environments/jmeter/values.yaml
          - values.yaml
