# Common parameters
# These parameters should be referenced from the source like this:
#  $ref: '#/components/parameters/<item-you-want>
components:
  parameters:
    CloudContext:
      name: cloudContext
      in: path
      description: A cloud platform which holds context for a workspace.
      required: true
      schema:
        $ref: '#/components/schemas/CloudPlatform'

    JobId:
      name: jobId
      in: path
      description: A String ID to used to identify a job
      required: true
      schema:
        type: string

    Limit:
      name: limit
      in: query
      description: The maximum number of items to return. Default 10
      required: false
      schema:
        type: integer
        minimum: 1
        default: 10

    MemberEmail:
      name: memberEmail
      in: path
      description: A user or group's email. Used for adding or removing IAM permissions
      required: true
      schema:
        type: string

    MinimumHighestRole:
      name: minimumHighestRole
      in: query
      description: |
        Returned workspace's highest role must be at least this. If
        minimumHighestRole is READER and requester only has DISCOVERER role,
        workspace is not returned. If not set, defaults to READER.
      required: false
      schema:
        $ref: '#/components/schemas/IamRole'
        # No "default:" because OpenAPI doesn't let you specify default with
        # $ref. See https://stackoverflow.com/a/68542868/6447189

    Name:
      name: name
      in: path
      description: A name used to identify an object in the workspace manager
      required: true
      schema:
        $ref: '#/components/schemas/Name'

    Offset:
      name: offset
      in: query
      description: The number of items to skip before starting to collect the result set.
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0

    ResourceId:
      name: resourceId
      in: path
      description: A UUID used to identify a controlled resource in a workspace.
      required: true
      schema:
        type: string
        format: uuid

    ResourceType:
      name: resource
      in: query
      description: Filter on a specific resource type
      required: false
      schema:
        $ref: '#/components/schemas/ResourceType'

    Role:
      name: role
      in: path
      description: An IAM role
      required: true
      schema:
        $ref: '#/components/schemas/IamRole'

    SasIpRange:
      name: sasIpRange
      in: query
      description: A single IP address or range of addresses separated by a dash to restrict a SAS token to
      required: false
      schema:
        type: string

    SasExpirationDuration:
      name: sasExpirationDuration
      in: query
      description: |
        The number of seconds until the SAS token should expire (optional). Default and maximum allowed values are
        set in configuration.
      required: false
      schema:
        type: integer
        format: int64

    SasEnableProxy:
      name: sasEnableProxy
      in: query
      description: |
        True to proxy SAS URLs through Azure Relay. Default false.
      required: false
      schema:
        type: boolean
        default: false

    SasPermissions:
      name: sasPermissions
      in: query
      required: false
      description: |
        Permissions associated with the SAS indicating what operations a client may perform on the resource. Must be a
        string consisting of some combination following available permissions:

        | Permission | Description |
        |------------|-------------|
        |`r`         | Read        |
        |`a`         | Add         |
        |`c`         | Create      |
        |`w`         | Write       |
        |`d`         | Delete      |
        |`l`         | List        |
        |`t`         | Tags        |

        For example:
          * To construct a SAS with permissions limited to read, write and list the caller would supply the string
        `rwl`.
          * To construct a SAS with permissions limited to add, create, write and delete, the caller would supply the
        string `acwd`.

        If the calling user does not have the requisite role against the workspace for the requested permissions, this
        operation will return a 403 Forbidden error.
      schema:
        type: string

    SasBlobName:
      name: sasBlobName
      in: query
      description:  Requests access to a single blob in a container
      required: false
      schema:
        type: string

    StewardshipType:
      name: stewardship
      in: query
      description: Filter on a stewardship type
      required: false
      schema:
        $ref: '#/components/schemas/StewardshipType'

    WorkspaceId:
      name: workspaceId
      in: path
      description: A UUID to used to identify a workspace in the workspace manager
      required: true
      schema:
        type: string
        format: uuid

    WorkspaceUserFacingId:
      name: workspaceUserFacingId
      in: path
      description: |
        Human-settable, mutable id. ID must have 3-63 characters, contain
        lowercase letters, numbers, dashes, or underscores, and start with
        lowercase letter or number.
      required: true
      schema:
        type: string

    FolderId:
      name: folderId
      in: path
      description: An UUID to identify a folder in a workspace.
      required: true
      schema:
        type: string
        format: uuid

    Platform:
      name: platform
      in: query
      description: The cloud platform (gcp, azure, aws)
      required: true
      schema:
        $ref: '#/components/schemas/CloudPlatform'

    WsmPolicyLocation:
      name: location
      in: query
      description: The geographic location of a data center (e.g. iowa, Illinois)
      required: false
      schema:
        type: string
