# All env variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams
env:
  db:
    host: jdbc:postgresql://${DATABASE_HOSTNAME:127.0.0.1}:5432
    init: ${INIT_DB:false}
    stairway:
      name: ${STAIRWAY_DATABASE_NAME:stairwaylib}
      pass: ${STAIRWAY_DATABASE_USER_PASSWORD:stairwaypwd}
      user: ${STAIRWAY_DATABASE_USER:stairwayuser}
    ws:
      name: ${DATABASE_NAME:wm}
      pass: ${DATABASE_USER_PASSWORD:wmpwd}
      user: ${DATABASE_USER:wmuser}
  tracing:
    enabled: ${CLOUD_TRACE_ENABLED:false}
    probability: ${SAMPLING_PROBABILITY:0}
    project-id: ${SERVICE_GOOGLE_PROJECT:broad-dsde-dev}
    sa-path: ${CLOUD_TRACE_SA_PATH:rendered/service-account.json}
  urls: # While we've traditionally thought of these as env specific and ok to hardcode, with kubernetes they may change
    sam: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org/}
    terra-datarepo: ${TERRA_DATAREPO_URL:https://jade.datarepo-dev.broadinstitute.org}

# Below here is non-deployment-specific

logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: workspace
  resources:
    cache.cachecontrol:
      max-age: 0
      must-revalidate: true
    static-locations: classpath:/api/

workspace:
  datarepo.instances:
    terra: ${env.urls.terra-datarepo}

  job:
    max-threads: 4
    polling-interval-seconds: 1
    resource-id: mc-terra-workspace-manager
    timeout-seconds: 1800

  sam.base-path: ${env.urls.sam}

  stairway-database:
    force-clean: true
    migrate-upgrade: ${env.db.init}
    password: ${env.db.stairway.pass}
    uri: ${env.db.host}/${env.db.stairway.name}
    username: ${env.db.stairway.user}

  status-check:
    frequency-ms: 60000
    staleness-threshold-ms: 600000

  tracing:
    enabled: ${env.tracing.enabled}
    probability: ${env.tracing.probability}
    project-id: ${env.tracing.project-id}
    sa-path: ${env.tracing.sa-path}

  workspace-database:
    initialize-on-start: ${env.db.init}
    password: ${env.db.ws.pass}
    upgrade-on-start: true
    uri: ${env.db.host}/${env.db.ws.name}
    username: ${env.db.ws.user}
