name: 'start-local-server'
description: 'Launch a bootrun server'
author: 'dd'
outputs:
  bootrunpid:
    description: 'pid of the gradle bootRun process'
    value: ${{ steps.launch.outputs.bootrunpid }}

runs:
  using: "composite"
  steps:
    - name: Launch the background process
      id: launch
      run: |
        # The redirect magic provides null input to work around a gradle bug and sends
        # both stdout and stderr to the log file.
        ./gradlew :service:bootRun --args='--spring.profiles.include=human-readable-logging'  2>&1 < /dev/null | tee wsm.log &
        bootrunpid=$!
        disown $bootrunpid
        echo "Launched WSM service pid $bootrunpid"
        echo "bootrunpid=$bootrunpid" >> $GITHUB_OUTPUT
      shell: bash

    - name: Wait for boot run to be ready
      id: wait-for-ready
      run: |
        # Give it some time before starting to poll.
        sleep 10
        started=1
        for i in `seq 1 240`;
        do
          echo "try server connect $i"
          if echo > /dev/tcp/localhost/8080
          then
            echo "Server started successfully"
            started=0
            break
          fi
          sleep 3
        done
        if [ "${started}" -eq "1" ]
        then
          echo "Server did not start successfully. Dumping log file"
          cat wsm.log
          exit 1
        fi
      shell: bash
