databaseChangeLog:
- changeSet:
    id: add application state
    author: dd
    changes:
    - addColumn:
        tableName: application
        columns:
          - column:
              name: state
              type: text
              remarks: |
                From WsmApplicationState: operating, deprecated, decommissioned
