env:
  db:
    host: ${DB_SERVER_NAME:127.0.0.1}:5432
    user: ${ADMIN_DB_USER_NAME:postgres}
  params:
    newDbUserName: ${NEW_DB_USER_NAME:newuser}
    newDbUserOid: ${NEW_DB_USER_OID:newuseroid}
    newDbName: ${DB_NAME:newdb}

spring:
  datasource:
    url: jdbc:postgresql://${env.db.host}/postgres?sslmode=require&authenticationPluginClassName=com.azure.identity.extensions.jdbc.postgresql.AzurePostgresqlAuthenticationPlugin
    username: ${env.db.user}

azureCreateDb:
  newDbUserName: ${env.params.newDbUserName}
  newDbUserOid: ${env.params.newDbUserOid}
  newDbName: ${env.params.newDbName}
