apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terra-workspace-manager-performance-role-binding
  labels:
    app: {{ .Chart.Name }}
roleRef:
  kind: Role
  name: terra-workspace-manager-performance-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Authorize specific service accounts:
  - kind: ServiceAccount
    name: terra-workspace-manager-performance-sa
