apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-influxdb-svc
  labels:
    app: {{ .Chart.Name }}-influxdb
spec:
  ports:
    - port: 8083
      name: http
      targetPort: 8083
    - port: 8086
      name: api
      targetPort: 8086
    - port: 2003
      name: graphite
      targetPort: 2003
  selector:
    app: {{ .Chart.Name }}-influxdb