apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-influxdb-configmap
  labels:
    jmeter_mode: {{ .Chart.Name }}-influxdb
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"
    # Configure the graphite api
    [[graphite]]
    enabled = true
    bind-address = ":2003" # If not set, is actually set to bind-address.
    database = "wsm"  # store graphite data in this database
