apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-influxdb-deployment
  labels:
    app: {{ .Chart.Name }}-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-influxdb
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-influxdb
    spec:
      serviceAccountName: {{ .Chart.Name }}-serviceaccount
      containers:
        - image: influxdb
          imagePullPolicy: IfNotPresent
          name: influxdb
          volumeMounts:
            - name: config-volume
              mountPath: /etc/influxdb
          ports:
            - containerPort: 8083
              name: influx
            - containerPort: 8086
              name: api
            - containerPort: 2003
              name: graphite
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}-influxdb-configmap
