apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-workers-svc
  labels:
    jmeter_mode: {{ .Chart.Name }}-worker
spec:
  clusterIP: None
  ports:
    - port: 1099
      name: first
      targetPort: 1099
    - port: 50000
      name: second
      targetPort: 50000
  selector:
    jmeter_mode: {{ .Chart.Name }}-worker