name: 'get-vault-token'
description: 'Retrieve vault token: devops disrecommends this; we still need it for rendering'
author: 'dd'
outputs:
  vault-token:
    description: "Vault token"
    value: ${{ steps.vault-token-step.vault-token }}
runs:
  using: "composite"
  steps:
    - name: Get vault token
      id: vault-token-step
      env:
        VAULT_ADDR: https://clotho.broadinstitute.org:8200
      shell: bash
      run: |
        VAULT_TOKEN=$(docker run --rm --cap-add IPC_LOCK \
          -e "VAULT_ADDR=${VAULT_ADDR}" \
          vault:1.1.0 \
          vault write -field token \
            auth/approle/login role_id=${{ secrets.VAULT_APPROLE_ROLE_ID }} \
            secret_id=${{ secrets.VAULT_APPROLE_SECRET_ID }})
        echo ::set-output name=vault-token::$VAULT_TOKEN
        echo ::add-mask::$VAULT_TOKEN
