apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-service-poc-deployment
  labels:
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      name: kernel-service-poc-service
      labels:
        version: v1
    spec:
      serviceAccountName: kernel-service-poc-service-sa
      containers:
      - name: kernel-service-poc
        image: gcr.io/terra-kernel-k8s/kernel-service-poc:0.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-user-creds
              key: username
        - name: DATABASE_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-user-creds
              key: password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-name
              key: db-name
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        env:
        - name: SQL_INSTANCE_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-instance-name
              key: name
        command: ["/cloud_sql_proxy",
                  "-instances=terra-kernel-k8s:us-central1:$(SQL_INSTANCE_NAME)=tcp:5432",
                  "-credential_file=/secrets/cloudsql/sql-creds.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: cloudsql-sa-creds
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
        - name: cloudsql-sa-creds
          secret:
            secretName: cloudsql-sa-creds
