apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: kernel-service-poc
resources:
- service-account.yaml
- psp.yaml
- role.yaml
- rolebinding.yaml
- istio-service.yaml
- deployment.yaml
- service.yaml
