name: 'integration-test'
description: 'Runs an integration test and uploads the results'
author: 'dd'
inputs:
  test-server:
    description: 'Test runner server specification file'
    required: true
    default: 'workspace-wsmtest.json'
  test:
    description: 'Test suite or config to run'
    required: true
    default: 'suites/FullIntegration.json'
  vault-token:
    description: 'Vault token for rendering'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set permissions and render test configurations
        run: |
          cd service
          chmod +x render_config.sh
          ./render_config.sh dev ${{ inputs.vault-token }}
          chmod +r rendered

    - name: Run the test
      run: |
        cd integration
        echo "Test Runner config"
        ./render-config.sh ${{ inputs.vault-token }}
        ./render-k8s-config.sh wsmtest ${{ inputs.vault-token }}
        export TEST_RUNNER_SERVER_SPECIFICATION_FILE=${{ inputs.test-server }}
        resultsDir=/tmp/results$RANDOM
        echo "Running test suite ${{ inputs.test }} on ${{ inputs.test-server }}"
        ../gradlew :integration:runTest --args="${{ inputs.test }} $resultsDir"
      shell: bash

  - name: Upload test results to Google Bucket
      if: ${{ always() }}
      run: |
        cd integration
        echo "Upload test results to Google Bucket"
        ../gradlew :integration:uploadResults --args="CompressDirectoryToTerraKernelK8S.json $resultsDir"
      shell: bash

    - name: Upload test results to BigQuery Test Runner Dataset
      if: ${{ always() }}
      run: |
        cd integration
        echo "Upload test results to BigQuery Test Runner Dataset"
        ../gradlew :integration:uploadResults --args="SummariesToTerraKernelK8SBigQuery.json $resultsDir"
      shell: bash
