name: 'render-config'
description: 'Collect the service account keys used for testing'
author: 'dd'
inputs:
  test-env:
    description: 'Test environment to render config for'
    required: true
  vault-token:
    description: 'Vault token for rendering'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set permissions and render test configurations
      run: |
        cd service
        chmod +x render_config.sh
        ./render_config.sh ${{ inputs.test-env }} ${{ inputs.vault-token }}
        chmod +r rendered
      shell: bash
