name: 'Render configs'
description: 'Runs the "render_configs.sh" script with vault token'
runs:
  using: "composite"
  steps:
    - name: Get Vault token
      id: vault-token-step
      env:
        VAULT_ADDR: https://clotho.broadinstitute.org:8200
      run: |
        VAULT_TOKEN=$(docker run --rm --cap-add IPC_LOCK \
          -e "VAULT_ADDR=${VAULT_ADDR}" \
          vault:1.1.0 \
          vault write -field token \
            auth/approle/login role_id=${{ secrets.VAULT_APPROLE_ROLE_ID }} \
            secret_id=${{ secrets.VAULT_APPROLE_SECRET_ID }})
        echo ::set-output name=vault-token::$VAULT_TOKEN
        echo ::add-mask::$VAULT_TOKEN
      shell: bash
    - name: Grant execute permission for render_config
      run: chmod +x render_config.sh
      shell: bash
    - name: Render configuration for tests
      run: $/render_config.sh ${{ steps.vault-token-step.outputs.vault-token }} dev
      shell: bash
    - name: Ensure read permissions for rendered files
      run: sudo chmod +r rendered
      shell: bash
