openapi: 3.0.0
info:
  title: Workspace Manager API
  description: |
    Workspace Manager REST API to manage workspaces.
  version: 0.0.1

servers:
  - url: http://localhost:8080

paths:
  '/status':
    get:
      description: |
        Returns the operational status of the service
      operationId: serviceStatus
      tags:
        - unauthenticated
      responses:
        200:
          description: Service is functional
          $ref: '#/components/responses/StatusResponse'
        500:
          description: Service is broken
          $ref: '#/components/responses/StatusResponse'

  '/api/v1/create':
    post:
      description: |
        Create a new Workspace. This should only be called by Folder Manager.
      operationId: create
      tags:
        - workspace
      requestBody:
        description: "Auth token, spend profile, and policy information from Folder Manager"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkspaceRequestBody'
      responses:
        200:
          description: OK
          $ref: '#/components/responses/CreateResponse'
        500:
          $ref: '#/components/responses/ErrorResponse'

components:
  schemas:
    ErrorReport:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
        causes:
          type: array
          items:
            type: string

    SystemStatus:
      type: object
      properties:
        ok:
          type: boolean
          description: status of this service
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string
    CreateWorkspaceRequestBody:
      type: object
      properties:
        id:
          description: The ID of the workspace
          type: string
          format: uuid
        authToken:
          description: Requesting user's auth token
          type: string
        spendProfile:
          description: UUID of provided spend profile
          type: string
          nullable: true
          format: uuid
        policies:
          description: Policies provided by the containing folder
          type: array
          nullable: true
          items:
            type: string
            format: uuid
    CreatedWorkspace:
      type: object
      properties:
        id:
          type: string
          description: UUID of a newly-created workspace

  responses:
    ErrorResponse:
      description: common error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    StatusResponse:
      description: common status response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'

    CreateResponse:
      description: Response to Create calls
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatedWorkspace'

