# This workflow runs the WSM full regression tests, including perf, integration, and
# resilience suites.

name: Test sparse checkout

on:
  push

jobs:
  sparse-checout:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Sparse checkout
        run: |
          mkdir -p terra-helmfile/environments
          cd terra-helmfile
          git init
          git config --global init.defaultBranch master
          ls -l .git
          cat .git/config
          git branch -m master
          cat .git/config
          git remote add origin https://broadbot:${{ secrets.BROADBOT_TOKEN }}@github.com/broadbot/terra-helmfile.git
          git config core.sparseCheckout true
          if [ -f .git/info/sparse-checkout ]; then
            rm .git/info/sparse-checkout
          fi
          echo "environments/" >> .git/info/sparse-checkout
          git checkout master
          ls -l
          ls -l environments
