# This workflow runs the WSM full regression tests, including perf, integration, and
# resilience suites.

name: Test sparse checkout

on:
  push

jobs:
  sparse-checout:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Check out environments and versions directories from terra-helmfile
        id: checkout-helm-versions-step
        uses: ./.github/actions/checkout-helm-versions
        with:
          repository: broadinstitute/terra-helmfile
          ref: master
          token: ${{ secrets.BROADBOT_TOKEN }}
          path: integration/terra-helmfile

      - name: Check dir
        run: |
          ls -l
          cat integration/terra-helmfile/versions/app/dev.yaml
