# Action for running a user-defined suite of integration tests against PRs. This test uses local
# server changes but runs a published version of the client, so it will not pick
# up local client changes.
#
# The idea of this workflow is to help debug integration tests. On your branch:
# - modify service and integration code
# - edit suites/TempTestSuite.json with the tests you want to run
# - push your branch to github - NO PR NEEDED!
# - use the workflow dispatch to run this workflow.
# This does not report results anywhere, so you have to check the github action page
# to see when it finished.

name: Run Integration Temp Test Suite
on:
  workflow_dispatch: {}

jobs:
  any-integration-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Initialize Postgres DB for local server test run
      env:
        PGPASSWORD: postgres
      run: psql -h 127.0.0.1 -U postgres -f ./service/local-dev/local-postgres-init.sql

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Write config
      id: config
      uses: ./.github/actions/write-credentials
      with:
        user-delegated-sa-b64: ${{ secrets.USER_DELEGATED_SA_DEV }}
        buffer-client-sa-b64: ${{ secrets.BUFFER_CLIENT_SA_DEV }}
        testrunner-sa-b64: ${{ secrets.TESTRUNNER_SA_DEV }}
        testrunner-k8s-sa-b64: ${{ secrets.TESTRUNNER_K8S_SA_DEV }}
        wsm-sa-b64: ${{ secrets.WSM_SA_DEV }}
        janitor-sa-b64: ${{ secrets.JANITOR_SA_DEV }}
        policy-client-sa-b64: ${{ secrets.POLICY_CLIENT_SA_DEV }}

    - name: Launch local server
      uses: ./.github/actions/start-local-server

    - name: Run the integration test suite
      id: integration-test
      uses: ./.github/actions/integration-test
      with:
        test-server: workspace-local.json
        test: suites/TempTestSuite.json

    - name: Archive WSM and TestRunner logs
      id: archive_logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: wsm-and-testrunner-logs
        path: |
          wsm.log
          ${{ steps.integration-test.outputs.results-dir }}
