# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test Runner Nightly Perf Tests

on:
  push

jobs:
  test-runner-perf:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up AdoptOpenJDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11
      - name: Get Vault token
        id: vault-token-step
        env:
          VAULT_ADDR: https://clotho.broadinstitute.org:8200
        run: |
          VAULT_TOKEN=$(docker run --rm --cap-add IPC_LOCK \
            -e "VAULT_ADDR=${VAULT_ADDR}" \
            vault:1.1.0 \
            vault write -field token \
              auth/approle/login role_id=${{ secrets.VAULT_APPROLE_ROLE_ID }} \
              secret_id=${{ secrets.VAULT_APPROLE_SECRET_ID }})
          echo ::set-output name=vault-token::$VAULT_TOKEN
          echo ::add-mask::$VAULT_TOKEN
      - name: Render configs for Test Runner
        run: |
          cd ${GITHUB_WORKSPACE}/${workingDir}/workspace-manager-clienttests
          ./render-config.sh ${{ steps.vault-token-step.outputs.vault-token }}
          ./render-k8s-config.sh wsmtest ${{ steps.vault-token-step.outputs.vault-token }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            .gradle/caches
            .gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Build the WSM client and run the Basic Perf test suite
        run: |
          ./gradlew :workspace-manager-client:build
          cd workspace-manager-clienttests
          export TEST_RUNNER_SERVER_SPECIFICATION_FILE=workspace-wsmtest.json
          echo "Running test suite"
          ./gradlew runTest --args="suites/BasicPerf.json /tmp/TestRunnerResults"

      - name: Upload test results to Google Bucket
        if: ${{ always() }}
        run: |
          cd workspace-manager-clienttests
          echo "Upload test results to Google Bucket"
          ./gradlew uploadResults --args="CompressDirectoryToTerraKernelK8S.json /tmp/TestRunnerResults"

      - name: Upload test results to BigQuery Test Runner Results Dataset
        if: ${{ always() }}
        run: |
          cd workspace-manager-clienttests
          echo "Upload test results to BigQuery Test Runner Dataset"
          ./gradlew uploadResults --args="SummariesToTerraKernelK8SBigQuery.json /tmp/TestRunnerResults"
