# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test Runner Nightly Integration Tests

on:
  push

jobs:
  test-runner-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up AdoptOpenJDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11
      # This step caches Gradle packages for reuse in the same VM instance.
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get Vault token
        id: vault-token-step
        env:
          VAULT_ADDR: https://clotho.broadinstitute.org:8200
        run: |
          VAULT_TOKEN=$(docker run --rm --cap-add IPC_LOCK \
            -e "VAULT_ADDR=${VAULT_ADDR}" \
            vault:1.1.0 \
            vault write -field token \
              auth/approle/login role_id=${{ secrets.VAULT_APPROLE_ROLE_ID }} \
              secret_id=${{ secrets.VAULT_APPROLE_SECRET_ID }})
          echo ::set-output name=vault-token::$VAULT_TOKEN
          echo ::add-mask::$VAULT_TOKEN
      - name: Set permissions and render test configurations
        run: |
          chmod +x render_config.sh
          ./render_config.sh dev ${{ steps.vault-token-step.outputs.vault-token }}
          chmod +r rendered
      # We can also set the env var in the GH action script to specify which server we are testing against.
      # This will be particularly helpful once we switch over to testing against any test env -- then it's just a change to the env var.
      # Please refer to https://github.com/DataBiosphere/terra-test-runner#override-the-server-from-the-command-line for more information.
      - name: Run the Basic Integration test suite
        run: |
          cd workspace-manager-clienttests
          echo "Test Runner config"
          ./render-config.sh ${{ steps.vault-token-step.outputs.vault-token }}
          ./render-k8s-config.sh wsmtest ${{ steps.vault-token-step.outputs.vault-token }}
          echo "Running test suite"
          ./gradlew runTest --args="suites/BasicIntegration.json /tmp/TestRunnerResults"

      - name: Upload test results to Google Bucket
        if: ${{ always() }}
        run: |
          cd workspace-manager-clienttests
          echo "Upload test results to Google Bucket"
          ./gradlew uploadResults --args="CompressDirectoryToBucket.json /tmp/TestRunnerResults"

      - name: Upload test results to BigQuery Test Runner Dataset
        if: ${{ always() }}
        run: |
          cd workspace-manager-clienttests
          echo "Upload test results to BigQuery Test Runner Dataset"
          ./gradlew uploadResults --args="SummariesToTerraKernelK8SBigQuery.json /tmp/TestRunnerResults"
