# This workflow is broken out because multiple other scheduled crons may all
# expect the test environment to be updated. Rather than them all potentially
# running the refresh at the same time, we do it once, earlier in the night, here.

name: WSM Test Env Refresh
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * *' # Run nightly at 1AM ET
jobs:
  refresh-environment:
    uses: broadinstitute/sherlock/.github/workflows/client-refresh-environment.yaml@main
    with:
      environment-name: wsmtest-eng
    permissions:
      id-token: 'write'
    secrets:
      sync-git-token: ${{ secrets.BROADBOT_TOKEN }}

  curl-version-endpoint:
    runs-on: ubuntu-latest
    needs: [refresh-environment]
    steps:
      - name: "Get wsmtest-eng TPS version"
        run: |
          echo "## Resulting TPS version: " >> $GITHUB_STEP_SUMMARY
          curl -X 'GET' \
            'https://tps.wsmtest-eng.bee.envs-terra.bio/version' \
            -H 'accept: */*' | jq >> $GITHUB_STEP_SUMMARY
