# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup PostgreSQL With Init Scripts
      uses: m4nu56/postgresql-action@1.0
      with:
        # Version of PostgreSQL to use
        postgresql version: 9.6
        # POSTGRES_INIT_SCRIPTS - directory containing DB init scripts
        postgresql init scripts: 'local-dev'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run unit tests
      env:
        DATABASE_USER: wmuser
        DATABASE_USER_PASSWORD: wmpwd
        DATABASE_NAME: wm
        STAIRWAY_DATABASE_USER: stairwayuser
        STAIRWAY_DATABASE_USER_PASSWORD: stairwaypwd
        STAIRWAY_DATABASE_NAME: stairwaylib
      run: ./gradlew unitTest
