# Workflow for testing new actions and workflows
#
# Github does not provide a way to run workflows that are not already merged to the
# default branch. Once a workflow that is configured for manual running is merged,
# then when you change it in a branch and execute your changes.
#
# The purpose of this workflow is to be a scratch space for developing workflows.
# Use it to prepare a workflow. When it is ready, you can copy the file to the
# proper name and merge from there.

name: Workflow Tester
on:
  workflow_dispatch: {}

jobs:
  server-startup-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Initialize Postgres DB for local server test run
        env:
          PGPASSWORD: postgres
        run: psql -h 127.0.0.1 -U postgres -f ./service/local-dev/local-postgres-init.sql

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Authenticate with Google Cloud as WSM
        id: 'obtain-owner-token'
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: "workspace-wsmtest@terra-kernel-k8s.iam.gserviceaccount.com"

      - name: Launch local server
        uses: ./.github/actions/start-local-server

      - name: Setup user delegated creds
        id: 'setup-user-delegated-creds'
        run: |
          USER_DELEGATED_SA_B64=${{ secrets.USER_DELEGATED_SA_DEV }}
          echo ::add-mask::$USER_DELEGATED_SA_B64
          USER_DELEGATED_SA=$(echo $USER_DELEGATED_SA_B64 | base64 --decode)
          echo ::add-mask::$USER_DELEGATED_SA
          echo $USER_DELEGATED_SA | jq .type
          mkdir -p config
          echo $USER_DELEGATED_SA > config/user-delegated-sa.json
          
          BUFFER_CLIENT_SA_B64=${{ secrets.BUFFER_CLIENT_SA_DEV }}
          echo ::add-mask::$BUFFER_CLIENT_SA_B64
          BUFFER_CLIENT_SA=$(echo $BUFFER_CLIENT_SA_B64 | base64 --decode)
          echo ::add-mask::$BUFFER_CLIENT_SA
          echo $BUFFER_CLIENT_SA | jq .type
          mkdir -p config
          echo $BUFFER_CLIENT_SA > config/buffer-client-sa.json
          
          TESTRUNNER_SA_B64=${{ secrets.TESTRUNNER_SA_DEV }}
          echo ::add-mask::$TESTRUNNER_SA_B64
          TESTRUNNER_SA=$(echo $TESTRUNNER_SA_B64 | base64 --decode)
          echo ::add-mask::$TESTRUNNER_SA
          echo $TESTRUNNER_SA | jq .type
          mkdir -p config
          echo $TESTRUNNER_SA > config/testrunner-sa.json

          TESTRUNNER_K8S_SA_B64=${{ secrets.TESTRUNNER_K8S_SA_DEV }}
          echo ::add-mask::$TESTRUNNER_K8S_SA_B64
          TESTRUNNER_K8S_SA=$(echo $TESTRUNNER_K8S_SA_B64 | base64 --decode)
          echo ::add-mask::$TESTRUNNER_K8S_SA
          mkdir -p config
          echo $TESTRUNNER_K8S_SA | jq -r ".data[\"ca.crt\"]" > config/testrunner-k8s-sa-key.txt
          echo $TESTRUNNER_K8S_SA | jq -r .data.token | base64 ---decode > config/testrunner-k8s-sa-token.txt

        shell: bash

#      - name: Authenticate with Google Cloud as Testrunner
#        id: 'obtain-testrunner-token'
#        uses: google-github-actions/auth@v2
#        with:
#          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
#          service_account: "testrunner-integration@terra-kernel-k8s.iam.gserviceaccount.com"

      - name: Run the integration test suite
        id: integration-test
        uses: ./.github/actions/integration-test
        with:
          test-server: workspace-local.json
          test: suites/PRIntegration.json


#      - name: Run unit tests
#        if: steps.skiptest.outputs.is-bump == 'no'
#        env:
#          # PRINT_STANDARD_STREAMS is temporary to let us inspect logs for a particular
#          # issue with Stairway serdes.
#          PRINT_STANDARD_STREAMS: please
#          TEST_ENV: local
#        run: ./gradlew :service:unitTest --scan